import type {
  AttendanceRecord,
  DashboardOverview,
  DashboardSession,
  Grade,
  Homework,
  LessonRecommendation,
  Student,
  TeachingGroup,
  Test,
  TopicAnalysis,
  TeacherNotification,
  TeacherProfile,
  TimetableEntry,
} from "./types";

export const demoSession: DashboardSession = {
  userId: "teacher-mueller",
  role: "school_admin",
  schoolId: "school-dayova-demo",
  displayName: "Frau Müller",
};

export const teachingGroups: TeachingGroup[] = [
  {
    id: "8a-mathematik",
    schoolId: demoSession.schoolId,
    classId: "class-8a",
    className: "8A",
    subjectId: "subject-math",
    subjectName: "Mathematik",
    teacherId: demoSession.userId,
    teacherName: demoSession.displayName,
    name: "8A – Mathematik – Frau Müller",
    studentCount: 26,
    openHomeworkCount: 2,
    upcomingTestCount: 1,
    riskStudentCount: 4,
    masteryScore: 68,
    isActive: true,
  },
  {
    id: "7b-mathematik",
    schoolId: demoSession.schoolId,
    classId: "class-7b",
    className: "7B",
    subjectId: "subject-math",
    subjectName: "Mathematik",
    teacherId: demoSession.userId,
    teacherName: demoSession.displayName,
    name: "7B – Mathematik – Frau Müller",
    studentCount: 24,
    openHomeworkCount: 1,
    upcomingTestCount: 1,
    riskStudentCount: 2,
    masteryScore: 76,
    isActive: true,
  },
  {
    id: "8a-physik",
    schoolId: demoSession.schoolId,
    classId: "class-8a",
    className: "8A",
    subjectId: "subject-physics",
    subjectName: "Physik",
    teacherId: demoSession.userId,
    teacherName: demoSession.displayName,
    name: "8A – Physik – Frau Müller",
    studentCount: 26,
    openHomeworkCount: 1,
    upcomingTestCount: 0,
    riskStudentCount: 3,
    masteryScore: 72,
    isActive: true,
  },
];

export const timetableEntries: TimetableEntry[] = [
  {
    id: "monday-8a-math",
    weekday: 1,
    startTime: "08:00",
    endTime: "08:45",
    room: "A 204",
    kind: "unterricht",
    teachingGroupId: "8a-mathematik",
  },
  {
    id: "monday-7b-math",
    weekday: 1,
    startTime: "09:50",
    endTime: "10:35",
    room: "B 112",
    kind: "unterricht",
    teachingGroupId: "7b-mathematik",
  },
  {
    id: "monday-8a-physics",
    weekday: 1,
    startTime: "11:40",
    endTime: "12:25",
    room: "P 03",
    kind: "unterricht",
    teachingGroupId: "8a-physik",
  },
  {
    id: "tuesday-8a-math",
    weekday: 2,
    startTime: "08:50",
    endTime: "09:35",
    room: "A 204",
    kind: "unterricht",
    teachingGroupId: "8a-mathematik",
  },
  {
    id: "tuesday-7b-math",
    weekday: 2,
    startTime: "10:45",
    endTime: "11:30",
    room: "B 112",
    kind: "unterricht",
    teachingGroupId: "7b-mathematik",
  },
  {
    id: "tuesday-yard-duty",
    weekday: 2,
    startTime: "11:30",
    endTime: "11:50",
    room: "Schulhof Nord",
    kind: "aufsicht",
    label: "Pausenaufsicht",
  },
  {
    id: "wednesday-8a-physics",
    weekday: 3,
    startTime: "08:00",
    endTime: "08:45",
    room: "P 03",
    kind: "unterricht",
    teachingGroupId: "8a-physik",
  },
  {
    id: "wednesday-8a-math",
    weekday: 3,
    startTime: "09:50",
    endTime: "10:35",
    room: "A 204",
    kind: "unterricht",
    teachingGroupId: "8a-mathematik",
  },
  {
    id: "thursday-7b-math",
    weekday: 4,
    startTime: "08:50",
    endTime: "09:35",
    room: "B 112",
    kind: "unterricht",
    teachingGroupId: "7b-mathematik",
  },
  {
    id: "thursday-8a-math",
    weekday: 4,
    startTime: "10:45",
    endTime: "11:30",
    room: "A 204",
    kind: "unterricht",
    teachingGroupId: "8a-mathematik",
  },
  {
    id: "thursday-conference",
    weekday: 4,
    startTime: "14:00",
    endTime: "15:00",
    room: "Konferenzraum",
    kind: "konferenz",
    label: "Fachkonferenz Mathematik",
  },
  {
    id: "friday-8a-math",
    weekday: 5,
    startTime: "08:00",
    endTime: "08:45",
    room: "A 204",
    kind: "unterricht",
    teachingGroupId: "8a-mathematik",
  },
  {
    id: "friday-8a-physics",
    weekday: 5,
    startTime: "09:50",
    endTime: "10:35",
    room: "P 03",
    kind: "unterricht",
    teachingGroupId: "8a-physik",
  },
];

export const students: Student[] = [
  {
    id: "student-lea",
    schoolId: demoSession.schoolId,
    classId: "class-8a",
    firstName: "Lea",
    lastName: "Schneider",
    email: "lea.schneider@schule.de",
    averageGrade: "2,7",
    homeworkCompletionRate: 88,
    knowledgeScore: 61,
    trend: "fallend",
    riskLevel: "hoch",
    supportFocus: "Bruchgleichungen",
    targetGradeFirstSemester: "2",
    targetGradeSecondSemester: "2",
  },
  {
    id: "student-emir",
    schoolId: demoSession.schoolId,
    classId: "class-8a",
    firstName: "Emir",
    lastName: "Yilmaz",
    email: "emir.yilmaz@schule.de",
    averageGrade: "2,3",
    homeworkCompletionRate: 76,
    knowledgeScore: 66,
    trend: "stabil",
    riskLevel: "mittel",
    supportFocus: "Äquivalenzumformungen",
    targetGradeFirstSemester: "2",
    targetGradeSecondSemester: "2",
  },
  {
    id: "student-sophie",
    schoolId: demoSession.schoolId,
    classId: "class-8a",
    firstName: "Sophie",
    lastName: "Becker",
    averageGrade: "1,6",
    homeworkCompletionRate: 100,
    knowledgeScore: 89,
    trend: "steigend",
    riskLevel: "niedrig",
    supportFocus: "Transferaufgaben",
    targetGradeFirstSemester: "1",
    targetGradeSecondSemester: "1",
  },
  {
    id: "student-noah",
    schoolId: demoSession.schoolId,
    classId: "class-8a",
    firstName: "Noah",
    lastName: "Klein",
    averageGrade: "3,1",
    homeworkCompletionRate: 62,
    knowledgeScore: 55,
    trend: "fallend",
    riskLevel: "hoch",
    supportFocus: "Vorzeichenregeln",
    targetGradeFirstSemester: "3",
  },
  {
    id: "student-mia",
    schoolId: demoSession.schoolId,
    classId: "class-8a",
    firstName: "Mia",
    lastName: "Hartmann",
    averageGrade: "2,0",
    homeworkCompletionRate: 94,
    knowledgeScore: 78,
    trend: "steigend",
    riskLevel: "niedrig",
    supportFocus: "Textaufgaben",
    targetGradeFirstSemester: "2",
    targetGradeSecondSemester: "2",
  },
  {
    id: "student-paul",
    schoolId: demoSession.schoolId,
    classId: "class-7b",
    firstName: "Paul",
    lastName: "Weber",
    email: "paul.weber@schule.de",
    averageGrade: "3,0",
    homeworkCompletionRate: 67,
    knowledgeScore: 58,
    trend: "fallend",
    riskLevel: "hoch",
    supportFocus: "Grundwert und Prozentwert unterscheiden",
    targetGradeFirstSemester: "3",
  },
  {
    id: "student-aylin",
    schoolId: demoSession.schoolId,
    classId: "class-7b",
    firstName: "Aylin",
    lastName: "Demir",
    email: "aylin.demir@schule.de",
    averageGrade: "2,4",
    homeworkCompletionRate: 79,
    knowledgeScore: 65,
    trend: "stabil",
    riskLevel: "mittel",
    supportFocus: "Prozentsatz aus Sachaufgaben ableiten",
    targetGradeFirstSemester: "2",
    targetGradeSecondSemester: "2",
  },
  {
    id: "student-jonas",
    schoolId: demoSession.schoolId,
    classId: "class-7b",
    firstName: "Jonas",
    lastName: "Fischer",
    averageGrade: "1,8",
    homeworkCompletionRate: 96,
    knowledgeScore: 84,
    trend: "steigend",
    riskLevel: "niedrig",
    supportFocus: "Mehrstufige Transferaufgaben",
    targetGradeFirstSemester: "2",
    targetGradeSecondSemester: "1",
  },
  {
    id: "student-emma",
    schoolId: demoSession.schoolId,
    classId: "class-7b",
    firstName: "Emma",
    lastName: "Richter",
    averageGrade: "2,1",
    homeworkCompletionRate: 91,
    knowledgeScore: 77,
    trend: "steigend",
    riskLevel: "niedrig",
    supportFocus: "Prozentuale Veränderungen begründen",
    targetGradeFirstSemester: "2",
    targetGradeSecondSemester: "2",
  },
  {
    id: "student-ben",
    schoolId: demoSession.schoolId,
    classId: "class-7b",
    firstName: "Ben",
    lastName: "Hoffmann",
    averageGrade: "3,2",
    homeworkCompletionRate: 54,
    knowledgeScore: 52,
    trend: "fallend",
    riskLevel: "hoch",
    supportFocus: "Grundwert sicher bestimmen",
    targetGradeFirstSemester: "3",
  },
];

export const homework: Homework[] = [
  {
    id: "hw-fraction-review",
    teachingGroupId: "8a-mathematik",
    title: "Bruchgleichungen festigen",
    description: "Aufgaben 4–10 bearbeiten und Rechenwege begründen.",
    dueDate: "2026-08-03T14:00:00.000Z",
    competency: "Bruchgleichungen",
    status: "offen",
    completionRate: 58,
    missingCount: 11,
  },
  {
    id: "hw-equivalence",
    teachingGroupId: "8a-mathematik",
    title: "Äquivalenzumformungen",
    description: "Kurzen Wissenscheck in der App abschließen.",
    dueDate: "2026-07-30T14:00:00.000Z",
    competency: "Äquivalenzumformungen",
    status: "korrektur",
    completionRate: 81,
    missingCount: 5,
  },
  {
    id: "hw-percent",
    teachingGroupId: "7b-mathematik",
    title: "Prozentrechnung im Alltag",
    description: "Drei Anwendungsaufgaben mit vollständigem Rechenweg lösen.",
    dueDate: "2026-08-04T14:00:00.000Z",
    competency: "Prozentrechnung",
    status: "offen",
    completionRate: 46,
    missingCount: 13,
  },
];

export const tests: Test[] = [
  {
    id: "test-fractions",
    teachingGroupId: "8a-mathematik",
    title: "Klassenarbeit Bruchgleichungen",
    description: "Bruchgleichungen, Äquivalenzumformungen und Transfer.",
    date: "2026-08-07T08:00:00.000Z",
    topics: ["Bruchgleichungen", "Äquivalenzumformungen"],
    status: "geplant",
    readinessScore: 64,
  },
  {
    id: "test-percent",
    teachingGroupId: "7b-mathematik",
    title: "Lernzielkontrolle Prozentrechnung",
    description: "Grundwert, Prozentwert und Prozentsatz.",
    date: "2026-08-11T10:00:00.000Z",
    topics: ["Prozentrechnung"],
    status: "geplant",
    readinessScore: 78,
  },
];

export const grades: Grade[] = [
  {
    id: "grade-lea-1",
    teachingGroupId: "8a-mathematik",
    studentId: "student-lea",
    assessmentTitle: "Lineare Gleichungen",
    assessmentType: "Test",
    value: "3+",
    weight: 2,
    competency: "Lineare Gleichungen",
    date: "2026-07-18T08:00:00.000Z",
    semester: 1,
  },
  {
    id: "grade-emir-1",
    teachingGroupId: "8a-mathematik",
    studentId: "student-emir",
    assessmentTitle: "Lineare Gleichungen",
    assessmentType: "Test",
    value: "2-",
    weight: 2,
    competency: "Lineare Gleichungen",
    date: "2026-07-18T08:00:00.000Z",
    semester: 1,
  },
  {
    id: "grade-sophie-1",
    teachingGroupId: "8a-mathematik",
    studentId: "student-sophie",
    assessmentTitle: "Lineare Gleichungen",
    assessmentType: "Test",
    value: "1",
    weight: 2,
    competency: "Lineare Gleichungen",
    date: "2026-07-18T08:00:00.000Z",
    semester: 1,
  },
  {
    id: "grade-lea-oral",
    teachingGroupId: "8a-mathematik",
    studentId: "student-lea",
    assessmentTitle: "Mündliche Mitarbeit",
    assessmentType: "Mündlich",
    value: "2-",
    weight: 1,
    competency: "Mathematisch argumentieren",
    date: "2026-07-22T08:00:00.000Z",
    semester: 2,
  },
  {
    id: "grade-emir-homework",
    teachingGroupId: "8a-mathematik",
    studentId: "student-emir",
    assessmentTitle: "Hausaufgabenportfolio",
    assessmentType: "Hausaufgabe",
    value: "2",
    weight: 1,
    competency: "Äquivalenzumformungen",
    date: "2026-07-24T08:00:00.000Z",
    semester: 2,
  },
  {
    id: "grade-sophie-oral",
    teachingGroupId: "8a-mathematik",
    studentId: "student-sophie",
    assessmentTitle: "Mündliche Mitarbeit",
    assessmentType: "Mündlich",
    value: "1",
    weight: 1,
    competency: "Mathematisch argumentieren",
    date: "2026-07-22T08:00:00.000Z",
    semester: 2,
  },
];

export const topicAnalyses: TopicAnalysis[] = [
  {
    id: "topic-fractions",
    teachingGroupId: "8a-mathematik",
    name: "Bruchgleichungen",
    masteryScore: 54,
    level: "unterstuetzung",
    trend: "fallend",
    affectedStudents: 14,
    misconception: "Nenner werden beim Umformen nicht auf beide Seiten angewendet.",
    priority: 1,
  },
  {
    id: "topic-equivalence",
    teachingGroupId: "8a-mathematik",
    name: "Äquivalenzumformungen",
    masteryScore: 67,
    level: "im_aufbau",
    trend: "stabil",
    affectedStudents: 9,
    misconception: "Rechenoperationen werden nicht vollständig notiert.",
    priority: 2,
  },
  {
    id: "topic-linear",
    teachingGroupId: "8a-mathematik",
    name: "Lineare Gleichungen",
    masteryScore: 82,
    level: "sicher",
    trend: "steigend",
    affectedStudents: 3,
    misconception: "Vereinzelte Vorzeichenfehler bei längeren Termen.",
    priority: 3,
  },
  {
    id: "topic-percent-applications",
    teachingGroupId: "7b-mathematik",
    name: "Prozentrechnung",
    masteryScore: 63,
    level: "im_aufbau",
    trend: "stabil",
    affectedStudents: 8,
    misconception: "Grundwert und Prozentwert werden in Sachaufgaben noch häufig vertauscht.",
    priority: 1,
  },
  {
    id: "topic-forces",
    teachingGroupId: "8a-physik",
    name: "Kräfte und Bewegung",
    masteryScore: 69,
    level: "im_aufbau",
    trend: "steigend",
    affectedStudents: 7,
    misconception: "Kraftpfeile werden noch nicht sicher aus Alltagssituationen abgeleitet.",
    priority: 1,
  },
];

export const lessonRecommendations: LessonRecommendation[] = [
  {
    id: "recommendation-fractions",
    teachingGroupId: "8a-mathematik",
    lessonTitle: "Bruchgleichungen vor der Klassenarbeit festigen",
    subject: "Mathematik",
    className: "8A",
    durationMinutes: 45,
    primaryTopic: "Bruchgleichungen",
    secondaryTopics: ["Äquivalenzumformungen", "Vorzeichenregeln"],
    lessonObjectives: [
      "Ein- und zweistufige Bruchgleichungen sicher lösen.",
      "Jeden Umformungsschritt nachvollziehbar begründen.",
    ],
    materialsNeeded: ["Diagnosekarten", "Differenzierte Übungsblätter", "Exit-Ticket"],
    phases: [
      {
        title: "Einstieg",
        durationMinutes: 5,
        description: "Einen typischen Fehler aus der letzten Analyse gemeinsam prüfen.",
        activities: ["Fehler markieren", "Korrekte Umformung begründen"],
      },
      {
        title: "Aktivierung",
        durationMinutes: 5,
        description: "Drei kurze Diagnoseaufgaben werden einzeln bearbeitet.",
        activities: ["Antwortkarten zeigen", "Unsicherheiten sammeln"],
      },
      {
        title: "Gemeinsame Erarbeitung",
        durationMinutes: 10,
        description: "Zwei Beispiele mit lautem Modellieren des Rechenwegs.",
        activities: ["Rechenweg strukturieren", "Nenner beseitigen"],
      },
      {
        title: "Differenzierte Übung",
        durationMinutes: 20,
        description: "Aufgaben nach aktuellem Wissensstand bearbeiten.",
        activities: ["Unterstützungsgruppe begleiten", "Transferaufgabe für starke Schüler:innen"],
      },
      {
        title: "Abschluss",
        durationMinutes: 5,
        description: "Exit-Ticket mit einem Rechenweg und einer kurzen Erklärung.",
        activities: ["Lösung abgeben", "Unterstützungsbedarf markieren"],
      },
    ],
    supportActivities: ["Schrittkarten nutzen", "Aufgaben mit vorgegebenem Hauptnenner"],
    coreActivities: ["Gemischte ein- und zweistufige Gleichungen"],
    advancedActivities: ["Fehlerdiagnose und eigene Transferaufgabe formulieren"],
    homeworkFollowUp: "Kurze App-Wiederholung zu Bruchgleichungen, fällig am 5. August.",
    classReadinessSummary:
      "Die Klasse kann arbeiten, aber 14 Schüler:innen benötigen vor der Klassenarbeit gezielte Wiederholung.",
    whyThisMattersNow:
      "Die Klassenarbeit findet am Freitag statt; Bruchgleichungen sind aktuell das schwächste prüfungsrelevante Thema.",
    signalsUsed: [
      "54 % Themenbeherrschung bei Bruchgleichungen",
      "14 betroffene Schüler:innen",
      "Klassenarbeit am 7. August",
      "Fallender Trend bei zwei Risikoschüler:innen",
    ],
    confidenceLevel: "hoch",
    generatedAt: "2026-07-30T06:30:00.000Z",
  },
];

export const dashboardOverview: DashboardOverview = {
  teacherName: demoSession.displayName,
  teachingGroups,
  todos: [
    {
      id: "todo-grades",
      type: "todo",
      title: "5 Noten fehlen",
      description: "Klassenarbeit Lineare Gleichungen · 8A Mathematik",
      teachingGroupId: "8a-mathematik",
      dueLabel: "Heute",
    },
    {
      id: "todo-homework",
      type: "todo",
      title: "Hausaufgabe prüfen",
      description: "Äquivalenzumformungen · 21 von 26 Abgaben",
      teachingGroupId: "8a-mathematik",
      dueLabel: "Heute",
    },
  ],
  warnings: [
    {
      id: "warning-fractions",
      type: "warning",
      title: "Bruchgleichungen brauchen Aufmerksamkeit",
      description: "14 Schüler:innen liegen unter dem erwarteten Wissensstand.",
      teachingGroupId: "8a-mathematik",
    },
  ],
  supportStudents: students.filter((student) => student.riskLevel !== "niedrig"),
  upcomingTests: tests,
  homeworkToReview: homework.filter((item) => item.status === "korrektur"),
  recommendations: lessonRecommendations,
};

export const attendanceRecords: AttendanceRecord[] = [
  ...students.map((student, index): AttendanceRecord => ({
    id: `attendance-2026-07-31-${student.id}`,
    schoolId: demoSession.schoolId,
    classId: student.classId,
    studentId: student.id,
    date: "2026-07-31",
    status: index === 1 ? "zu_frueh_gegangen" : index === 3 ? "krank" : "anwesend",
    note: index === 1 ? "Nach der 5. Stunde abgeholt" : undefined,
    sickNoteAvailable: index === 3,
    isExcused: index === 3,
  })),
  ...students.slice(0, 2).map((student, index): AttendanceRecord => ({
    id: `attendance-2026-07-${28 + index}-${student.id}`,
    schoolId: demoSession.schoolId,
    classId: student.classId,
    studentId: student.id,
    date: `2026-07-${28 + index}`,
    status: index === 0 ? "nicht_erschienen" : "krank",
    sickNoteAvailable: index === 1,
    isExcused: index === 1,
  })),
];

export const teacherNotifications: TeacherNotification[] = [
  {
    id: "notification-homework",
    title: "Hausaufgabe zur Prüfung bereit",
    description: "21 Abgaben in der 8A können jetzt geprüft werden.",
    createdAt: "2026-07-31T07:45:00.000Z",
    href: "/lehrkraefte/hausaufgaben",
    read: false,
    tone: "brand",
  },
  {
    id: "notification-risk",
    title: "Neuer Unterstützungsbedarf",
    description: "Bei Lea und Noah zeigt sich ein fallender Lerntrend.",
    createdAt: "2026-07-31T06:30:00.000Z",
    href: "/lehrkraefte/klassen/class-8a/schueler",
    read: false,
    tone: "warning",
  },
  {
    id: "notification-test",
    title: "Testvorbereitung wurde aktualisiert",
    description: "Die Themenanalyse für die Mathematikarbeit der 8A ist aktuell.",
    createdAt: "2026-07-30T14:15:00.000Z",
    href: "/lehrkraefte/analysen/8a-mathematik",
    read: true,
    tone: "neutral",
  },
];

export const teacherProfile: TeacherProfile = {
  id: demoSession.userId,
  name: demoSession.displayName,
  email: "franziska.mueller@albert-einstein-schule.de",
  schoolName: "Albert-Einstein-Schule",
  subjects: ["Mathematik", "Physik"],
  classTeacherOf: ["8A"],
};
